# Site settings
title: Kylin Soong . Blog
email: kylinsoong.1214@gmail.com
description: "Kylin Soong Blog"
#baseurl: ""
url: ksoong.org
twitter_username: kylinsoong
github_username:  kylinsoong
author: Kylin Soong


# Build settings
markdown: kramdown
permalink: pretty

paginate: 15
paginate_path: "/page:num"

# Global Configuration
source: .
destination: ./_site
safe: true
exclude: []
include: ['.htaccess']
timezone: Asia/Shanghai
encoding: UTF-8

# Build Command Options
future: true
#lsi: true
limit_posts: 10000

# Serve Command Options
port: 8888
host: localhost
baseurl: ""
detach: false

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "default"

#collections:
#  my_collection:
#    output: true
#    permalink: /awesome/:path/
#    foo: bar
# Comments   
disqus:
  config: false
  id: need register

duoshuo:
  config: true
  id: ksoong   
