name: ksoong
title: ksoong
org: ksoong
base_url: ''

google_analytics: UA-18521069-1

profiles: 
  production: 
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    base_url: http://kylinsoong.github.io/ 
    deploy: 
      host: github_pages 
      branch: master
